services:
  - type: web
    name: django-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings
      - key: PYTHON_VERSION
        value: 3.13.3
